/*
 * generated by Xtext 2.40.0
 */
grammar InternalWorkflow;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package agent.adaption.xtext.workflow.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package agent.adaption.xtext.workflow.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import agent.adaption.xtext.workflow.services.WorkflowGrammarAccess;

}
@parser::members {
	private WorkflowGrammarAccess grammarAccess;

	public void setGrammarAccess(WorkflowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleWorkflowStructure
entryRuleWorkflowStructure
:
{ before(grammarAccess.getWorkflowStructureRule()); }
	 ruleWorkflowStructure
{ after(grammarAccess.getWorkflowStructureRule()); } 
	 EOF 
;

// Rule WorkflowStructure
ruleWorkflowStructure 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getWorkflowStructureAccess().getGroup()); }
		(rule__WorkflowStructure__Group__0)
		{ after(grammarAccess.getWorkflowStructureAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleWorkflow
entryRuleWorkflow
:
{ before(grammarAccess.getWorkflowRule()); }
	 ruleWorkflow
{ after(grammarAccess.getWorkflowRule()); } 
	 EOF 
;

// Rule Workflow
ruleWorkflow 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getWorkflowAccess().getAlternatives()); }
		(rule__Workflow__Alternatives)
		{ after(grammarAccess.getWorkflowAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMBoolExpr
entryRuleMBoolExpr
:
{ before(grammarAccess.getMBoolExprRule()); }
	 ruleMBoolExpr
{ after(grammarAccess.getMBoolExprRule()); } 
	 EOF 
;

// Rule MBoolExpr
ruleMBoolExpr 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMBoolExprAccess().getAlternatives()); }
		(rule__MBoolExpr__Alternatives)
		{ after(grammarAccess.getMBoolExprAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSequence
entryRuleSequence
:
{ before(grammarAccess.getSequenceRule()); }
	 ruleSequence
{ after(grammarAccess.getSequenceRule()); } 
	 EOF 
;

// Rule Sequence
ruleSequence 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSequenceAccess().getGroup()); }
		(rule__Sequence__Group__0)
		{ after(grammarAccess.getSequenceAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTask
entryRuleTask
:
{ before(grammarAccess.getTaskRule()); }
	 ruleTask
{ after(grammarAccess.getTaskRule()); } 
	 EOF 
;

// Rule Task
ruleTask 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTaskAccess().getGroup()); }
		(rule__Task__Group__0)
		{ after(grammarAccess.getTaskAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLoop
entryRuleLoop
:
{ before(grammarAccess.getLoopRule()); }
	 ruleLoop
{ after(grammarAccess.getLoopRule()); } 
	 EOF 
;

// Rule Loop
ruleLoop 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLoopAccess().getGroup()); }
		(rule__Loop__Group__0)
		{ after(grammarAccess.getLoopAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleDecision
entryRuleDecision
:
{ before(grammarAccess.getDecisionRule()); }
	 ruleDecision
{ after(grammarAccess.getDecisionRule()); } 
	 EOF 
;

// Rule Decision
ruleDecision 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDecisionAccess().getGroup()); }
		(rule__Decision__Group__0)
		{ after(grammarAccess.getDecisionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleGuardedWorkflow
entryRuleGuardedWorkflow
:
{ before(grammarAccess.getGuardedWorkflowRule()); }
	 ruleGuardedWorkflow
{ after(grammarAccess.getGuardedWorkflowRule()); } 
	 EOF 
;

// Rule GuardedWorkflow
ruleGuardedWorkflow 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getGuardedWorkflowAccess().getGroup()); }
		(rule__GuardedWorkflow__Group__0)
		{ after(grammarAccess.getGuardedWorkflowAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMBoolExpr_Impl
entryRuleMBoolExpr_Impl
:
{ before(grammarAccess.getMBoolExpr_ImplRule()); }
	 ruleMBoolExpr_Impl
{ after(grammarAccess.getMBoolExpr_ImplRule()); } 
	 EOF 
;

// Rule MBoolExpr_Impl
ruleMBoolExpr_Impl 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMBoolExpr_ImplAccess().getGroup()); }
		(rule__MBoolExpr_Impl__Group__0)
		{ after(grammarAccess.getMBoolExpr_ImplAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleValue
entryRuleValue
:
{ before(grammarAccess.getValueRule()); }
	 ruleValue
{ after(grammarAccess.getValueRule()); } 
	 EOF 
;

// Rule Value
ruleValue 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getValueAccess().getGroup()); }
		(rule__Value__Group__0)
		{ after(grammarAccess.getValueAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBoolValue
entryRuleBoolValue
:
{ before(grammarAccess.getBoolValueRule()); }
	 ruleBoolValue
{ after(grammarAccess.getBoolValueRule()); } 
	 EOF 
;

// Rule BoolValue
ruleBoolValue 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBoolValueAccess().getGroup()); }
		(rule__BoolValue__Group__0)
		{ after(grammarAccess.getBoolValueAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBoolComp
entryRuleBoolComp
:
{ before(grammarAccess.getBoolCompRule()); }
	 ruleBoolComp
{ after(grammarAccess.getBoolCompRule()); } 
	 EOF 
;

// Rule BoolComp
ruleBoolComp 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBoolCompAccess().getGroup()); }
		(rule__BoolComp__Group__0)
		{ after(grammarAccess.getBoolCompAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleNot
entryRuleNot
:
{ before(grammarAccess.getNotRule()); }
	 ruleNot
{ after(grammarAccess.getNotRule()); } 
	 EOF 
;

// Rule Not
ruleNot 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNotAccess().getGroup()); }
		(rule__Not__Group__0)
		{ after(grammarAccess.getNotAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleRelComp
entryRuleRelComp
:
{ before(grammarAccess.getRelCompRule()); }
	 ruleRelComp
{ after(grammarAccess.getRelCompRule()); } 
	 EOF 
;

// Rule RelComp
ruleRelComp 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRelCompAccess().getGroup()); }
		(rule__RelComp__Group__0)
		{ after(grammarAccess.getRelCompAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAtom
entryRuleAtom
:
{ before(grammarAccess.getAtomRule()); }
	 ruleAtom
{ after(grammarAccess.getAtomRule()); } 
	 EOF 
;

// Rule Atom
ruleAtom 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAtomAccess().getGroup()); }
		(rule__Atom__Group__0)
		{ after(grammarAccess.getAtomAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEInt
entryRuleEInt
:
{ before(grammarAccess.getEIntRule()); }
	 ruleEInt
{ after(grammarAccess.getEIntRule()); } 
	 EOF 
;

// Rule EInt
ruleEInt 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEIntAccess().getGroup()); }
		(rule__EInt__Group__0)
		{ after(grammarAccess.getEIntAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule BoolOp
ruleBoolOp
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolOpAccess().getAlternatives()); }
		(rule__BoolOp__Alternatives)
		{ after(grammarAccess.getBoolOpAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule RelOp
ruleRelOp
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRelOpAccess().getAlternatives()); }
		(rule__RelOp__Alternatives)
		{ after(grammarAccess.getRelOpAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Workflow__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getWorkflowAccess().getSequenceParserRuleCall_0()); }
		ruleSequence
		{ after(grammarAccess.getWorkflowAccess().getSequenceParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getWorkflowAccess().getTaskParserRuleCall_1()); }
		ruleTask
		{ after(grammarAccess.getWorkflowAccess().getTaskParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getWorkflowAccess().getLoopParserRuleCall_2()); }
		ruleLoop
		{ after(grammarAccess.getWorkflowAccess().getLoopParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getWorkflowAccess().getDecisionParserRuleCall_3()); }
		ruleDecision
		{ after(grammarAccess.getWorkflowAccess().getDecisionParserRuleCall_3()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MBoolExpr__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMBoolExprAccess().getMBoolExpr_ImplParserRuleCall_0()); }
		ruleMBoolExpr_Impl
		{ after(grammarAccess.getMBoolExprAccess().getMBoolExpr_ImplParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getValueParserRuleCall_1()); }
		ruleValue
		{ after(grammarAccess.getMBoolExprAccess().getValueParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getBoolValueParserRuleCall_2()); }
		ruleBoolValue
		{ after(grammarAccess.getMBoolExprAccess().getBoolValueParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getBoolCompParserRuleCall_3()); }
		ruleBoolComp
		{ after(grammarAccess.getMBoolExprAccess().getBoolCompParserRuleCall_3()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getNotParserRuleCall_4()); }
		ruleNot
		{ after(grammarAccess.getMBoolExprAccess().getNotParserRuleCall_4()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getRelCompParserRuleCall_5()); }
		ruleRelComp
		{ after(grammarAccess.getMBoolExprAccess().getRelCompParserRuleCall_5()); }
	)
	|
	(
		{ before(grammarAccess.getMBoolExprAccess().getAtomParserRuleCall_6()); }
		ruleAtom
		{ after(grammarAccess.getMBoolExprAccess().getAtomParserRuleCall_6()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolOp__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolOpAccess().getANDEnumLiteralDeclaration_0()); }
		('AND')
		{ after(grammarAccess.getBoolOpAccess().getANDEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getBoolOpAccess().getOREnumLiteralDeclaration_1()); }
		('OR')
		{ after(grammarAccess.getBoolOpAccess().getOREnumLiteralDeclaration_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelOp__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRelOpAccess().getLESS_THANEnumLiteralDeclaration_0()); }
		('LESS_THAN')
		{ after(grammarAccess.getRelOpAccess().getLESS_THANEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getRelOpAccess().getGREATER_THANEnumLiteralDeclaration_1()); }
		('GREATER_THAN')
		{ after(grammarAccess.getRelOpAccess().getGREATER_THANEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getRelOpAccess().getNOT_EQUALEnumLiteralDeclaration_2()); }
		('NOT_EQUAL')
		{ after(grammarAccess.getRelOpAccess().getNOT_EQUALEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getRelOpAccess().getLESS_EQUALEnumLiteralDeclaration_3()); }
		('LESS_EQUAL')
		{ after(grammarAccess.getRelOpAccess().getLESS_EQUALEnumLiteralDeclaration_3()); }
	)
	|
	(
		{ before(grammarAccess.getRelOpAccess().getGREATER_EQUALEnumLiteralDeclaration_4()); }
		('GREATER_EQUAL')
		{ after(grammarAccess.getRelOpAccess().getGREATER_EQUALEnumLiteralDeclaration_4()); }
	)
	|
	(
		{ before(grammarAccess.getRelOpAccess().getEQUALEnumLiteralDeclaration_5()); }
		('EQUAL')
		{ after(grammarAccess.getRelOpAccess().getEQUALEnumLiteralDeclaration_5()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__WorkflowStructure__Group__0__Impl
	rule__WorkflowStructure__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getWorkflowStructureAccess().getWorkflowStructureKeyword_0()); }
	'WorkflowStructure'
	{ after(grammarAccess.getWorkflowStructureAccess().getWorkflowStructureKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__WorkflowStructure__Group__1__Impl
	rule__WorkflowStructure__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getWorkflowStructureAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getWorkflowStructureAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__WorkflowStructure__Group__2__Impl
	rule__WorkflowStructure__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getWorkflowStructureAccess().getWorkflowspecKeyword_2()); }
	'workflowspec'
	{ after(grammarAccess.getWorkflowStructureAccess().getWorkflowspecKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__WorkflowStructure__Group__3__Impl
	rule__WorkflowStructure__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getWorkflowStructureAccess().getWorkflowspecAssignment_3()); }
	(rule__WorkflowStructure__WorkflowspecAssignment_3)
	{ after(grammarAccess.getWorkflowStructureAccess().getWorkflowspecAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__WorkflowStructure__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__WorkflowStructure__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getWorkflowStructureAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getWorkflowStructureAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Sequence__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__0__Impl
	rule__Sequence__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getSequenceKeyword_0()); }
	'Sequence'
	{ after(grammarAccess.getSequenceAccess().getSequenceKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__1__Impl
	rule__Sequence__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__2__Impl
	rule__Sequence__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getSubworkflowsKeyword_2()); }
	'subworkflows'
	{ after(grammarAccess.getSequenceAccess().getSubworkflowsKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__3__Impl
	rule__Sequence__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__4__Impl
	rule__Sequence__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_4()); }
	(rule__Sequence__SubworkflowsAssignment_4)
	{ after(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__5__Impl
	rule__Sequence__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getGroup_5()); }
	(rule__Sequence__Group_5__0)*
	{ after(grammarAccess.getSequenceAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__6__Impl
	rule__Sequence__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group__7__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_7()); }
	'}'
	{ after(grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Sequence__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group_5__0__Impl
	rule__Sequence__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getCommaKeyword_5_0()); }
	','
	{ after(grammarAccess.getSequenceAccess().getCommaKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Sequence__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_5_1()); }
	(rule__Sequence__SubworkflowsAssignment_5_1)
	{ after(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Task__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Task__Group__0__Impl
	rule__Task__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTaskAccess().getTaskKeyword_0()); }
	'Task'
	{ after(grammarAccess.getTaskAccess().getTaskKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Task__Group__1__Impl
	rule__Task__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTaskAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getTaskAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Task__Group__2__Impl
	rule__Task__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTaskAccess().getIDKeyword_2()); }
	'ID'
	{ after(grammarAccess.getTaskAccess().getIDKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Task__Group__3__Impl
	rule__Task__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTaskAccess().getIDAssignment_3()); }
	(rule__Task__IDAssignment_3)
	{ after(grammarAccess.getTaskAccess().getIDAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Task__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTaskAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getTaskAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Loop__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Loop__Group__0__Impl
	rule__Loop__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLoopAccess().getLoopKeyword_0()); }
	'Loop'
	{ after(grammarAccess.getLoopAccess().getLoopKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Loop__Group__1__Impl
	rule__Loop__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLoopAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getLoopAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Loop__Group__2__Impl
	rule__Loop__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLoopAccess().getLoopKeyword_2()); }
	'loop'
	{ after(grammarAccess.getLoopAccess().getLoopKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Loop__Group__3__Impl
	rule__Loop__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLoopAccess().getLoopAssignment_3()); }
	(rule__Loop__LoopAssignment_3)
	{ after(grammarAccess.getLoopAccess().getLoopAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Loop__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLoopAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getLoopAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Decision__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__0__Impl
	rule__Decision__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getDecisionKeyword_0()); }
	'Decision'
	{ after(grammarAccess.getDecisionAccess().getDecisionKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__1__Impl
	rule__Decision__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__2__Impl
	rule__Decision__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getOptionsKeyword_2()); }
	'options'
	{ after(grammarAccess.getDecisionAccess().getOptionsKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__3__Impl
	rule__Decision__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__4__Impl
	rule__Decision__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getOptionsAssignment_4()); }
	(rule__Decision__OptionsAssignment_4)
	{ after(grammarAccess.getDecisionAccess().getOptionsAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__5__Impl
	rule__Decision__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getGroup_5()); }
	(rule__Decision__Group_5__0)*
	{ after(grammarAccess.getDecisionAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__6__Impl
	rule__Decision__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group__7__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_7()); }
	'}'
	{ after(grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Decision__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group_5__0__Impl
	rule__Decision__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getCommaKeyword_5_0()); }
	','
	{ after(grammarAccess.getDecisionAccess().getCommaKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Decision__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getDecisionAccess().getOptionsAssignment_5_1()); }
	(rule__Decision__OptionsAssignment_5_1)
	{ after(grammarAccess.getDecisionAccess().getOptionsAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__GuardedWorkflow__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__0__Impl
	rule__GuardedWorkflow__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getGuardedWorkflowKeyword_0()); }
	'GuardedWorkflow'
	{ after(grammarAccess.getGuardedWorkflowAccess().getGuardedWorkflowKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__1__Impl
	rule__GuardedWorkflow__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getLeftCurlyBracketKeyword_1()); }
	'{'
	{ after(grammarAccess.getGuardedWorkflowAccess().getLeftCurlyBracketKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__2__Impl
	rule__GuardedWorkflow__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getBodyKeyword_2()); }
	'body'
	{ after(grammarAccess.getGuardedWorkflowAccess().getBodyKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__3__Impl
	rule__GuardedWorkflow__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getBodyAssignment_3()); }
	(rule__GuardedWorkflow__BodyAssignment_3)
	{ after(grammarAccess.getGuardedWorkflowAccess().getBodyAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__4__Impl
	rule__GuardedWorkflow__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getGuardKeyword_4()); }
	'guard'
	{ after(grammarAccess.getGuardedWorkflowAccess().getGuardKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__5__Impl
	rule__GuardedWorkflow__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getGuardAssignment_5()); }
	(rule__GuardedWorkflow__GuardAssignment_5)
	{ after(grammarAccess.getGuardedWorkflowAccess().getGuardAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__GuardedWorkflow__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getGuardedWorkflowAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getGuardedWorkflowAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MBoolExpr_Impl__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MBoolExpr_Impl__Group__0__Impl
	rule__MBoolExpr_Impl__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MBoolExpr_Impl__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprAction_0()); }
	()
	{ after(grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MBoolExpr_Impl__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MBoolExpr_Impl__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MBoolExpr_Impl__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprKeyword_1()); }
	'MBoolExpr'
	{ after(grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Value__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group__0__Impl
	rule__Value__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getValueAction_0()); }
	()
	{ after(grammarAccess.getValueAccess().getValueAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group__1__Impl
	rule__Value__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getValueKeyword_1()); }
	'Value'
	{ after(grammarAccess.getValueAccess().getValueKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group__2__Impl
	rule__Value__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getValueAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group__3__Impl
	rule__Value__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getGroup_3()); }
	(rule__Value__Group_3__0)?
	{ after(grammarAccess.getValueAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getValueAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Value__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group_3__0__Impl
	rule__Value__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getValueKeyword_3_0()); }
	'value'
	{ after(grammarAccess.getValueAccess().getValueKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Value__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getValueAccess().getValueAssignment_3_1()); }
	(rule__Value__ValueAssignment_3_1)
	{ after(grammarAccess.getValueAccess().getValueAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BoolValue__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolValue__Group__0__Impl
	rule__BoolValue__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolValueAccess().getBoolValueAction_0()); }
	()
	{ after(grammarAccess.getBoolValueAccess().getBoolValueAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolValue__Group__1__Impl
	rule__BoolValue__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolValueAccess().getValueAssignment_1()); }
	(rule__BoolValue__ValueAssignment_1)?
	{ after(grammarAccess.getBoolValueAccess().getValueAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolValue__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolValueAccess().getBoolValueKeyword_2()); }
	'BoolValue'
	{ after(grammarAccess.getBoolValueAccess().getBoolValueKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BoolComp__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__0__Impl
	rule__BoolComp__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getBoolCompAction_0()); }
	()
	{ after(grammarAccess.getBoolCompAccess().getBoolCompAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__1__Impl
	rule__BoolComp__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getBoolCompKeyword_1()); }
	'BoolComp'
	{ after(grammarAccess.getBoolCompAccess().getBoolCompKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__2__Impl
	rule__BoolComp__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getBoolCompAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__3__Impl
	rule__BoolComp__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getGroup_3()); }
	(rule__BoolComp__Group_3__0)?
	{ after(grammarAccess.getBoolCompAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__4__Impl
	rule__BoolComp__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getGroup_4()); }
	(rule__BoolComp__Group_4__0)?
	{ after(grammarAccess.getBoolCompAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__5__Impl
	rule__BoolComp__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getGroup_5()); }
	(rule__BoolComp__Group_5__0)?
	{ after(grammarAccess.getBoolCompAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getBoolCompAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BoolComp__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_3__0__Impl
	rule__BoolComp__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getOpKeyword_3_0()); }
	'op'
	{ after(grammarAccess.getBoolCompAccess().getOpKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getOpAssignment_3_1()); }
	(rule__BoolComp__OpAssignment_3_1)
	{ after(grammarAccess.getBoolCompAccess().getOpAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BoolComp__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_4__0__Impl
	rule__BoolComp__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getRightKeyword_4_0()); }
	'right'
	{ after(grammarAccess.getBoolCompAccess().getRightKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getRightAssignment_4_1()); }
	(rule__BoolComp__RightAssignment_4_1)
	{ after(grammarAccess.getBoolCompAccess().getRightAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BoolComp__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_5__0__Impl
	rule__BoolComp__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getLeftKeyword_5_0()); }
	'left'
	{ after(grammarAccess.getBoolCompAccess().getLeftKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BoolComp__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBoolCompAccess().getLeftAssignment_5_1()); }
	(rule__BoolComp__LeftAssignment_5_1)
	{ after(grammarAccess.getBoolCompAccess().getLeftAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Not__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__0__Impl
	rule__Not__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getNotAction_0()); }
	()
	{ after(grammarAccess.getNotAccess().getNotAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__1__Impl
	rule__Not__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getNotKeyword_1()); }
	'Not'
	{ after(grammarAccess.getNotAccess().getNotKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__2__Impl
	rule__Not__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getNotAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__3__Impl
	rule__Not__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getGroup_3()); }
	(rule__Not__Group_3__0)?
	{ after(grammarAccess.getNotAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__4__Impl
	rule__Not__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getGroup_4()); }
	(rule__Not__Group_4__0)?
	{ after(grammarAccess.getNotAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getNotAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Not__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group_3__0__Impl
	rule__Not__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getOpKeyword_3_0()); }
	'op'
	{ after(grammarAccess.getNotAccess().getOpKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getOpAssignment_3_1()); }
	(rule__Not__OpAssignment_3_1)
	{ after(grammarAccess.getNotAccess().getOpAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Not__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group_4__0__Impl
	rule__Not__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getExprKeyword_4_0()); }
	'expr'
	{ after(grammarAccess.getNotAccess().getExprKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Not__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNotAccess().getExprAssignment_4_1()); }
	(rule__Not__ExprAssignment_4_1)
	{ after(grammarAccess.getNotAccess().getExprAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__RelComp__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__0__Impl
	rule__RelComp__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getRelCompAction_0()); }
	()
	{ after(grammarAccess.getRelCompAccess().getRelCompAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__1__Impl
	rule__RelComp__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getRelCompKeyword_1()); }
	'RelComp'
	{ after(grammarAccess.getRelCompAccess().getRelCompKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__2__Impl
	rule__RelComp__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getRelCompAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__3__Impl
	rule__RelComp__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getGroup_3()); }
	(rule__RelComp__Group_3__0)?
	{ after(grammarAccess.getRelCompAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__4__Impl
	rule__RelComp__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getGroup_4()); }
	(rule__RelComp__Group_4__0)?
	{ after(grammarAccess.getRelCompAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__5__Impl
	rule__RelComp__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getGroup_5()); }
	(rule__RelComp__Group_5__0)?
	{ after(grammarAccess.getRelCompAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getRightCurlyBracketKeyword_6()); }
	'}'
	{ after(grammarAccess.getRelCompAccess().getRightCurlyBracketKeyword_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__RelComp__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_3__0__Impl
	rule__RelComp__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getOpKeyword_3_0()); }
	'op'
	{ after(grammarAccess.getRelCompAccess().getOpKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getOpAssignment_3_1()); }
	(rule__RelComp__OpAssignment_3_1)
	{ after(grammarAccess.getRelCompAccess().getOpAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__RelComp__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_4__0__Impl
	rule__RelComp__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getLeftKeyword_4_0()); }
	'left'
	{ after(grammarAccess.getRelCompAccess().getLeftKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getLeftAssignment_4_1()); }
	(rule__RelComp__LeftAssignment_4_1)
	{ after(grammarAccess.getRelCompAccess().getLeftAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__RelComp__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_5__0__Impl
	rule__RelComp__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getRightKeyword_5_0()); }
	'right'
	{ after(grammarAccess.getRelCompAccess().getRightKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__RelComp__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRelCompAccess().getRightAssignment_5_1()); }
	(rule__RelComp__RightAssignment_5_1)
	{ after(grammarAccess.getRelCompAccess().getRightAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Atom__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group__0__Impl
	rule__Atom__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getAtomAction_0()); }
	()
	{ after(grammarAccess.getAtomAccess().getAtomAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group__1__Impl
	rule__Atom__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getAtomKeyword_1()); }
	'Atom'
	{ after(grammarAccess.getAtomAccess().getAtomKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group__2__Impl
	rule__Atom__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getLeftCurlyBracketKeyword_2()); }
	'{'
	{ after(grammarAccess.getAtomAccess().getLeftCurlyBracketKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group__3__Impl
	rule__Atom__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getGroup_3()); }
	(rule__Atom__Group_3__0)?
	{ after(grammarAccess.getAtomAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getRightCurlyBracketKeyword_4()); }
	'}'
	{ after(grammarAccess.getAtomAccess().getRightCurlyBracketKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Atom__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group_3__0__Impl
	rule__Atom__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getMeasureIDKeyword_3_0()); }
	'measureID'
	{ after(grammarAccess.getAtomAccess().getMeasureIDKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Atom__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAtomAccess().getMeasureIDAssignment_3_1()); }
	(rule__Atom__MeasureIDAssignment_3_1)
	{ after(grammarAccess.getAtomAccess().getMeasureIDAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EInt__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__0__Impl
	rule__EInt__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__WorkflowStructure__WorkflowspecAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getWorkflowStructureAccess().getWorkflowspecWorkflowParserRuleCall_3_0()); }
		ruleWorkflow
		{ after(grammarAccess.getWorkflowStructureAccess().getWorkflowspecWorkflowParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__SubworkflowsAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_4_0()); }
		ruleWorkflow
		{ after(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Sequence__SubworkflowsAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_5_1_0()); }
		ruleWorkflow
		{ after(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Task__IDAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTaskAccess().getIDEStringParserRuleCall_3_0()); }
		ruleEString
		{ after(grammarAccess.getTaskAccess().getIDEStringParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Loop__LoopAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLoopAccess().getLoopGuardedWorkflowParserRuleCall_3_0()); }
		ruleGuardedWorkflow
		{ after(grammarAccess.getLoopAccess().getLoopGuardedWorkflowParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__OptionsAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_4_0()); }
		ruleGuardedWorkflow
		{ after(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Decision__OptionsAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_5_1_0()); }
		ruleGuardedWorkflow
		{ after(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__BodyAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getGuardedWorkflowAccess().getBodyWorkflowParserRuleCall_3_0()); }
		ruleWorkflow
		{ after(grammarAccess.getGuardedWorkflowAccess().getBodyWorkflowParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__GuardedWorkflow__GuardAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getGuardedWorkflowAccess().getGuardMBoolExprParserRuleCall_5_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getGuardedWorkflowAccess().getGuardMBoolExprParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Value__ValueAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getValueAccess().getValueEIntParserRuleCall_3_1_0()); }
		ruleEInt
		{ after(grammarAccess.getValueAccess().getValueEIntParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolValue__ValueAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolValueAccess().getValueValueKeyword_1_0()); }
		(
			{ before(grammarAccess.getBoolValueAccess().getValueValueKeyword_1_0()); }
			'value'
			{ after(grammarAccess.getBoolValueAccess().getValueValueKeyword_1_0()); }
		)
		{ after(grammarAccess.getBoolValueAccess().getValueValueKeyword_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__OpAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolCompAccess().getOpBoolOpEnumRuleCall_3_1_0()); }
		ruleBoolOp
		{ after(grammarAccess.getBoolCompAccess().getOpBoolOpEnumRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__RightAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolCompAccess().getRightMBoolExprParserRuleCall_4_1_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getBoolCompAccess().getRightMBoolExprParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BoolComp__LeftAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBoolCompAccess().getLeftMBoolExprParserRuleCall_5_1_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getBoolCompAccess().getLeftMBoolExprParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__OpAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNotAccess().getOpEStringParserRuleCall_3_1_0()); }
		ruleEString
		{ after(grammarAccess.getNotAccess().getOpEStringParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Not__ExprAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNotAccess().getExprMBoolExprParserRuleCall_4_1_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getNotAccess().getExprMBoolExprParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__OpAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRelCompAccess().getOpRelOpEnumRuleCall_3_1_0()); }
		ruleRelOp
		{ after(grammarAccess.getRelCompAccess().getOpRelOpEnumRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__LeftAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRelCompAccess().getLeftMBoolExprParserRuleCall_4_1_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getRelCompAccess().getLeftMBoolExprParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__RelComp__RightAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRelCompAccess().getRightMBoolExprParserRuleCall_5_1_0()); }
		ruleMBoolExpr
		{ after(grammarAccess.getRelCompAccess().getRightMBoolExprParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Atom__MeasureIDAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAtomAccess().getMeasureIDEStringParserRuleCall_3_1_0()); }
		ruleEString
		{ after(grammarAccess.getAtomAccess().getMeasureIDEStringParserRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
