/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class WorkflowGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class WorkflowStructureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.WorkflowStructure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkflowStructureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWorkflowspecKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cWorkflowspecAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cWorkflowspecWorkflowParserRuleCall_3_0 = (RuleCall)cWorkflowspecAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//WorkflowStructure returns WorkflowStructure:
		//    'WorkflowStructure'
		//    '{'
		//        'workflowspec' workflowspec=Workflow
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WorkflowStructure'
		//'{'
		//    'workflowspec' workflowspec=Workflow
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'WorkflowStructure'
		public Keyword getWorkflowStructureKeyword_0() { return cWorkflowStructureKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'workflowspec'
		public Keyword getWorkflowspecKeyword_2() { return cWorkflowspecKeyword_2; }
		
		//workflowspec=Workflow
		public Assignment getWorkflowspecAssignment_3() { return cWorkflowspecAssignment_3; }
		
		//Workflow
		public RuleCall getWorkflowspecWorkflowParserRuleCall_3_0() { return cWorkflowspecWorkflowParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class WorkflowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Workflow");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSequenceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTaskParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLoopParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDecisionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Workflow returns Workflow:
		//    Sequence | Task | Loop | Decision;
		@Override public ParserRule getRule() { return rule; }
		
		//Sequence | Task | Loop | Decision
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Sequence
		public RuleCall getSequenceParserRuleCall_0() { return cSequenceParserRuleCall_0; }
		
		//Task
		public RuleCall getTaskParserRuleCall_1() { return cTaskParserRuleCall_1; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_2() { return cLoopParserRuleCall_2; }
		
		//Decision
		public RuleCall getDecisionParserRuleCall_3() { return cDecisionParserRuleCall_3; }
	}
	public class MBoolExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.MBoolExpr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMBoolExpr_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBoolValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBoolCompParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cNotParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cRelCompParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cAtomParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//MBoolExpr returns MBoolExpr:
		//    MBoolExpr_Impl | Value | BoolValue | BoolComp | Not | RelComp | Atom;
		@Override public ParserRule getRule() { return rule; }
		
		//MBoolExpr_Impl | Value | BoolValue | BoolComp | Not | RelComp | Atom
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MBoolExpr_Impl
		public RuleCall getMBoolExpr_ImplParserRuleCall_0() { return cMBoolExpr_ImplParserRuleCall_0; }
		
		//Value
		public RuleCall getValueParserRuleCall_1() { return cValueParserRuleCall_1; }
		
		//BoolValue
		public RuleCall getBoolValueParserRuleCall_2() { return cBoolValueParserRuleCall_2; }
		
		//BoolComp
		public RuleCall getBoolCompParserRuleCall_3() { return cBoolCompParserRuleCall_3; }
		
		//Not
		public RuleCall getNotParserRuleCall_4() { return cNotParserRuleCall_4; }
		
		//RelComp
		public RuleCall getRelCompParserRuleCall_5() { return cRelCompParserRuleCall_5; }
		
		//Atom
		public RuleCall getAtomParserRuleCall_6() { return cAtomParserRuleCall_6; }
	}
	public class SequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Sequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSubworkflowsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSubworkflowsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSubworkflowsWorkflowParserRuleCall_4_0 = (RuleCall)cSubworkflowsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSubworkflowsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSubworkflowsWorkflowParserRuleCall_5_1_0 = (RuleCall)cSubworkflowsAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Sequence returns Sequence:
		//    'Sequence'
		//    '{'
		//        'subworkflows' '{' subworkflows+=Workflow ( "," subworkflows+=Workflow)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Sequence'
		//'{'
		//    'subworkflows' '{' subworkflows+=Workflow ( "," subworkflows+=Workflow)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Sequence'
		public Keyword getSequenceKeyword_0() { return cSequenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'subworkflows'
		public Keyword getSubworkflowsKeyword_2() { return cSubworkflowsKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//subworkflows+=Workflow
		public Assignment getSubworkflowsAssignment_4() { return cSubworkflowsAssignment_4; }
		
		//Workflow
		public RuleCall getSubworkflowsWorkflowParserRuleCall_4_0() { return cSubworkflowsWorkflowParserRuleCall_4_0; }
		
		//( "," subworkflows+=Workflow)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//subworkflows+=Workflow
		public Assignment getSubworkflowsAssignment_5_1() { return cSubworkflowsAssignment_5_1; }
		
		//Workflow
		public RuleCall getSubworkflowsWorkflowParserRuleCall_5_1_0() { return cSubworkflowsWorkflowParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cIDKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIDAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIDEStringParserRuleCall_3_0 = (RuleCall)cIDAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Task returns Task:
		//    'Task'
		//    '{'
		//        'ID' ID=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Task'
		//'{'
		//    'ID' ID=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Task'
		public Keyword getTaskKeyword_0() { return cTaskKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'ID'
		public Keyword getIDKeyword_2() { return cIDKeyword_2; }
		
		//ID=EString
		public Assignment getIDAssignment_3() { return cIDAssignment_3; }
		
		//EString
		public RuleCall getIDEStringParserRuleCall_3_0() { return cIDEStringParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLoopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLoopAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLoopGuardedWorkflowParserRuleCall_3_0 = (RuleCall)cLoopAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Loop returns Loop:
		//    'Loop'
		//    '{'
		//        'loop' loop=GuardedWorkflow
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loop'
		//'{'
		//    'loop' loop=GuardedWorkflow
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'loop'
		public Keyword getLoopKeyword_2() { return cLoopKeyword_2; }
		
		//loop=GuardedWorkflow
		public Assignment getLoopAssignment_3() { return cLoopAssignment_3; }
		
		//GuardedWorkflow
		public RuleCall getLoopGuardedWorkflowParserRuleCall_3_0() { return cLoopGuardedWorkflowParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class DecisionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Decision");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDecisionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOptionsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOptionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOptionsGuardedWorkflowParserRuleCall_4_0 = (RuleCall)cOptionsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOptionsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOptionsGuardedWorkflowParserRuleCall_5_1_0 = (RuleCall)cOptionsAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Decision returns Decision:
		//    'Decision'
		//    '{'
		//        'options' '{' options+=GuardedWorkflow ( "," options+=GuardedWorkflow)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Decision'
		//'{'
		//    'options' '{' options+=GuardedWorkflow ( "," options+=GuardedWorkflow)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Decision'
		public Keyword getDecisionKeyword_0() { return cDecisionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'options'
		public Keyword getOptionsKeyword_2() { return cOptionsKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//options+=GuardedWorkflow
		public Assignment getOptionsAssignment_4() { return cOptionsAssignment_4; }
		
		//GuardedWorkflow
		public RuleCall getOptionsGuardedWorkflowParserRuleCall_4_0() { return cOptionsGuardedWorkflowParserRuleCall_4_0; }
		
		//( "," options+=GuardedWorkflow)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//options+=GuardedWorkflow
		public Assignment getOptionsAssignment_5_1() { return cOptionsAssignment_5_1; }
		
		//GuardedWorkflow
		public RuleCall getOptionsGuardedWorkflowParserRuleCall_5_1_0() { return cOptionsGuardedWorkflowParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class GuardedWorkflowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.GuardedWorkflow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGuardedWorkflowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBodyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBodyWorkflowParserRuleCall_3_0 = (RuleCall)cBodyAssignment_3.eContents().get(0);
		private final Keyword cGuardKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cGuardAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cGuardMBoolExprParserRuleCall_5_0 = (RuleCall)cGuardAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GuardedWorkflow returns GuardedWorkflow:
		//    'GuardedWorkflow'
		//    '{'
		//        'body' body=Workflow
		//        'guard' guard=MBoolExpr
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GuardedWorkflow'
		//'{'
		//    'body' body=Workflow
		//    'guard' guard=MBoolExpr
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GuardedWorkflow'
		public Keyword getGuardedWorkflowKeyword_0() { return cGuardedWorkflowKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'body'
		public Keyword getBodyKeyword_2() { return cBodyKeyword_2; }
		
		//body=Workflow
		public Assignment getBodyAssignment_3() { return cBodyAssignment_3; }
		
		//Workflow
		public RuleCall getBodyWorkflowParserRuleCall_3_0() { return cBodyWorkflowParserRuleCall_3_0; }
		
		//'guard'
		public Keyword getGuardKeyword_4() { return cGuardKeyword_4; }
		
		//guard=MBoolExpr
		public Assignment getGuardAssignment_5() { return cGuardAssignment_5; }
		
		//MBoolExpr
		public RuleCall getGuardMBoolExprParserRuleCall_5_0() { return cGuardMBoolExprParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class MBoolExpr_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.MBoolExpr_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMBoolExprAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMBoolExprKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//MBoolExpr_Impl returns MBoolExpr:
		//    {MBoolExpr}
		//    'MBoolExpr'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{MBoolExpr}
		//'MBoolExpr'
		public Group getGroup() { return cGroup; }
		
		//{MBoolExpr}
		public Action getMBoolExprAction_0() { return cMBoolExprAction_0; }
		
		//'MBoolExpr'
		public Keyword getMBoolExprKeyword_1() { return cMBoolExprKeyword_1; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Value");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cValueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Value returns Value:
		//    {Value}
		//    'Value'
		//    '{'
		//        ('value' value=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Value}
		//'Value'
		//'{'
		//    ('value' value=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Value}
		public Action getValueAction_0() { return cValueAction_0; }
		
		//'Value'
		public Keyword getValueKeyword_1() { return cValueKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EInt
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_3_1_0() { return cValueEIntParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BoolValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.BoolValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValueValueKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		private final Keyword cBoolValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//BoolValue returns BoolValue:
		//    {BoolValue}
		//    (value?='value')?
		//    'BoolValue'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{BoolValue}
		//(value?='value')?
		//'BoolValue'
		public Group getGroup() { return cGroup; }
		
		//{BoolValue}
		public Action getBoolValueAction_0() { return cBoolValueAction_0; }
		
		//(value?='value')?
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//'value'
		public Keyword getValueValueKeyword_1_0() { return cValueValueKeyword_1_0; }
		
		//'BoolValue'
		public Keyword getBoolValueKeyword_2() { return cBoolValueKeyword_2; }
	}
	public class BoolCompElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.BoolComp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoolCompAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolCompKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOpKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOpAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOpBoolOpEnumRuleCall_3_1_0 = (RuleCall)cOpAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRightKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRightAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRightMBoolExprParserRuleCall_4_1_0 = (RuleCall)cRightAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLeftAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLeftMBoolExprParserRuleCall_5_1_0 = (RuleCall)cLeftAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//BoolComp returns BoolComp:
		//    {BoolComp}
		//    'BoolComp'
		//    '{'
		//        ('op' op=BoolOp)?
		//        ('right' right=MBoolExpr)?
		//        ('left' left=MBoolExpr)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BoolComp}
		//'BoolComp'
		//'{'
		//    ('op' op=BoolOp)?
		//    ('right' right=MBoolExpr)?
		//    ('left' left=MBoolExpr)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{BoolComp}
		public Action getBoolCompAction_0() { return cBoolCompAction_0; }
		
		//'BoolComp'
		public Keyword getBoolCompKeyword_1() { return cBoolCompKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('op' op=BoolOp)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'op'
		public Keyword getOpKeyword_3_0() { return cOpKeyword_3_0; }
		
		//op=BoolOp
		public Assignment getOpAssignment_3_1() { return cOpAssignment_3_1; }
		
		//BoolOp
		public RuleCall getOpBoolOpEnumRuleCall_3_1_0() { return cOpBoolOpEnumRuleCall_3_1_0; }
		
		//('right' right=MBoolExpr)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'right'
		public Keyword getRightKeyword_4_0() { return cRightKeyword_4_0; }
		
		//right=MBoolExpr
		public Assignment getRightAssignment_4_1() { return cRightAssignment_4_1; }
		
		//MBoolExpr
		public RuleCall getRightMBoolExprParserRuleCall_4_1_0() { return cRightMBoolExprParserRuleCall_4_1_0; }
		
		//('left' left=MBoolExpr)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'left'
		public Keyword getLeftKeyword_5_0() { return cLeftKeyword_5_0; }
		
		//left=MBoolExpr
		public Assignment getLeftAssignment_5_1() { return cLeftAssignment_5_1; }
		
		//MBoolExpr
		public RuleCall getLeftMBoolExprParserRuleCall_5_1_0() { return cLeftMBoolExprParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class NotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Not");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNotKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOpKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOpAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOpEStringParserRuleCall_3_1_0 = (RuleCall)cOpAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cExprKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cExprAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cExprMBoolExprParserRuleCall_4_1_0 = (RuleCall)cExprAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Not returns Not:
		//    {Not}
		//    'Not'
		//    '{'
		//        ('op' op=EString)?
		//        ('expr' expr=MBoolExpr)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Not}
		//'Not'
		//'{'
		//    ('op' op=EString)?
		//    ('expr' expr=MBoolExpr)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Not}
		public Action getNotAction_0() { return cNotAction_0; }
		
		//'Not'
		public Keyword getNotKeyword_1() { return cNotKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('op' op=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'op'
		public Keyword getOpKeyword_3_0() { return cOpKeyword_3_0; }
		
		//op=EString
		public Assignment getOpAssignment_3_1() { return cOpAssignment_3_1; }
		
		//EString
		public RuleCall getOpEStringParserRuleCall_3_1_0() { return cOpEStringParserRuleCall_3_1_0; }
		
		//('expr' expr=MBoolExpr)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'expr'
		public Keyword getExprKeyword_4_0() { return cExprKeyword_4_0; }
		
		//expr=MBoolExpr
		public Assignment getExprAssignment_4_1() { return cExprAssignment_4_1; }
		
		//MBoolExpr
		public RuleCall getExprMBoolExprParserRuleCall_4_1_0() { return cExprMBoolExprParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RelCompElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.RelComp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelCompAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelCompKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOpKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOpAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOpRelOpEnumRuleCall_3_1_0 = (RuleCall)cOpAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLeftAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLeftMBoolExprParserRuleCall_4_1_0 = (RuleCall)cLeftAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRightMBoolExprParserRuleCall_5_1_0 = (RuleCall)cRightAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RelComp returns RelComp:
		//    {RelComp}
		//    'RelComp'
		//    '{'
		//        ('op' op=RelOp)?
		//        ('left' left=MBoolExpr)?
		//        ('right' right=MBoolExpr)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RelComp}
		//'RelComp'
		//'{'
		//    ('op' op=RelOp)?
		//    ('left' left=MBoolExpr)?
		//    ('right' right=MBoolExpr)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RelComp}
		public Action getRelCompAction_0() { return cRelCompAction_0; }
		
		//'RelComp'
		public Keyword getRelCompKeyword_1() { return cRelCompKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('op' op=RelOp)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'op'
		public Keyword getOpKeyword_3_0() { return cOpKeyword_3_0; }
		
		//op=RelOp
		public Assignment getOpAssignment_3_1() { return cOpAssignment_3_1; }
		
		//RelOp
		public RuleCall getOpRelOpEnumRuleCall_3_1_0() { return cOpRelOpEnumRuleCall_3_1_0; }
		
		//('left' left=MBoolExpr)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'left'
		public Keyword getLeftKeyword_4_0() { return cLeftKeyword_4_0; }
		
		//left=MBoolExpr
		public Assignment getLeftAssignment_4_1() { return cLeftAssignment_4_1; }
		
		//MBoolExpr
		public RuleCall getLeftMBoolExprParserRuleCall_4_1_0() { return cLeftMBoolExprParserRuleCall_4_1_0; }
		
		//('right' right=MBoolExpr)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'right'
		public Keyword getRightKeyword_5_0() { return cRightKeyword_5_0; }
		
		//right=MBoolExpr
		public Assignment getRightAssignment_5_1() { return cRightAssignment_5_1; }
		
		//MBoolExpr
		public RuleCall getRightMBoolExprParserRuleCall_5_1_0() { return cRightMBoolExprParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.Atom");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAtomAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAtomKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cMeasureIDKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMeasureIDAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMeasureIDEStringParserRuleCall_3_1_0 = (RuleCall)cMeasureIDAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Atom returns Atom:
		//    {Atom}
		//    'Atom'
		//    '{'
		//        ('measureID' measureID=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Atom}
		//'Atom'
		//'{'
		//    ('measureID' measureID=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Atom}
		public Action getAtomAction_0() { return cAtomAction_0; }
		
		//'Atom'
		public Keyword getAtomKeyword_1() { return cAtomKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('measureID' measureID=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'measureID'
		public Keyword getMeasureIDKeyword_3_0() { return cMeasureIDKeyword_3_0; }
		
		//measureID=EString
		public Assignment getMeasureIDAssignment_3_1() { return cMeasureIDAssignment_3_1; }
		
		//EString
		public RuleCall getMeasureIDEStringParserRuleCall_3_1_0() { return cMeasureIDEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class BoolOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.BoolOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cANDANDKeyword_0_0 = (Keyword)cANDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORORKeyword_1_0 = (Keyword)cOREnumLiteralDeclaration_1.eContents().get(0);
		
		//enum BoolOp returns BoolOp:
		//                AND = 'AND' | OR = 'OR';
		public EnumRule getRule() { return rule; }
		
		//AND = 'AND' | OR = 'OR'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AND = 'AND'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_0() { return cANDEnumLiteralDeclaration_0; }
		
		//'AND'
		public Keyword getANDANDKeyword_0_0() { return cANDANDKeyword_0_0; }
		
		//OR = 'OR'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_1() { return cOREnumLiteralDeclaration_1; }
		
		//'OR'
		public Keyword getORORKeyword_1_0() { return cORORKeyword_1_0; }
	}
	public class RelOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "agent.adaption.xtext.workflow.Workflow.RelOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLESS_THANEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLESS_THANLESS_THANKeyword_0_0 = (Keyword)cLESS_THANEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGREATER_THANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGREATER_THANGREATER_THANKeyword_1_0 = (Keyword)cGREATER_THANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNOT_EQUALEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNOT_EQUALNOT_EQUALKeyword_2_0 = (Keyword)cNOT_EQUALEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLESS_EQUALEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLESS_EQUALLESS_EQUALKeyword_3_0 = (Keyword)cLESS_EQUALEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGREATER_EQUALEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGREATER_EQUALGREATER_EQUALKeyword_4_0 = (Keyword)cGREATER_EQUALEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cEQUALEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cEQUALEQUALKeyword_5_0 = (Keyword)cEQUALEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum RelOp returns RelOp:
		//                LESS_THAN = 'LESS_THAN' | GREATER_THAN = 'GREATER_THAN' | NOT_EQUAL = 'NOT_EQUAL' | LESS_EQUAL = 'LESS_EQUAL' | GREATER_EQUAL = 'GREATER_EQUAL' | EQUAL = 'EQUAL';
		public EnumRule getRule() { return rule; }
		
		//LESS_THAN = 'LESS_THAN' | GREATER_THAN = 'GREATER_THAN' | NOT_EQUAL = 'NOT_EQUAL' | LESS_EQUAL = 'LESS_EQUAL' | GREATER_EQUAL = 'GREATER_EQUAL' | EQUAL = 'EQUAL'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LESS_THAN = 'LESS_THAN'
		public EnumLiteralDeclaration getLESS_THANEnumLiteralDeclaration_0() { return cLESS_THANEnumLiteralDeclaration_0; }
		
		//'LESS_THAN'
		public Keyword getLESS_THANLESS_THANKeyword_0_0() { return cLESS_THANLESS_THANKeyword_0_0; }
		
		//GREATER_THAN = 'GREATER_THAN'
		public EnumLiteralDeclaration getGREATER_THANEnumLiteralDeclaration_1() { return cGREATER_THANEnumLiteralDeclaration_1; }
		
		//'GREATER_THAN'
		public Keyword getGREATER_THANGREATER_THANKeyword_1_0() { return cGREATER_THANGREATER_THANKeyword_1_0; }
		
		//NOT_EQUAL = 'NOT_EQUAL'
		public EnumLiteralDeclaration getNOT_EQUALEnumLiteralDeclaration_2() { return cNOT_EQUALEnumLiteralDeclaration_2; }
		
		//'NOT_EQUAL'
		public Keyword getNOT_EQUALNOT_EQUALKeyword_2_0() { return cNOT_EQUALNOT_EQUALKeyword_2_0; }
		
		//LESS_EQUAL = 'LESS_EQUAL'
		public EnumLiteralDeclaration getLESS_EQUALEnumLiteralDeclaration_3() { return cLESS_EQUALEnumLiteralDeclaration_3; }
		
		//'LESS_EQUAL'
		public Keyword getLESS_EQUALLESS_EQUALKeyword_3_0() { return cLESS_EQUALLESS_EQUALKeyword_3_0; }
		
		//GREATER_EQUAL = 'GREATER_EQUAL'
		public EnumLiteralDeclaration getGREATER_EQUALEnumLiteralDeclaration_4() { return cGREATER_EQUALEnumLiteralDeclaration_4; }
		
		//'GREATER_EQUAL'
		public Keyword getGREATER_EQUALGREATER_EQUALKeyword_4_0() { return cGREATER_EQUALGREATER_EQUALKeyword_4_0; }
		
		//EQUAL = 'EQUAL'
		public EnumLiteralDeclaration getEQUALEnumLiteralDeclaration_5() { return cEQUALEnumLiteralDeclaration_5; }
		
		//'EQUAL'
		public Keyword getEQUALEQUALKeyword_5_0() { return cEQUALEQUALKeyword_5_0; }
	}
	
	private final WorkflowStructureElements pWorkflowStructure;
	private final WorkflowElements pWorkflow;
	private final MBoolExprElements pMBoolExpr;
	private final SequenceElements pSequence;
	private final TaskElements pTask;
	private final LoopElements pLoop;
	private final DecisionElements pDecision;
	private final EStringElements pEString;
	private final GuardedWorkflowElements pGuardedWorkflow;
	private final MBoolExpr_ImplElements pMBoolExpr_Impl;
	private final ValueElements pValue;
	private final BoolValueElements pBoolValue;
	private final BoolCompElements pBoolComp;
	private final NotElements pNot;
	private final RelCompElements pRelComp;
	private final AtomElements pAtom;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final BoolOpElements eBoolOp;
	private final RelOpElements eRelOp;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WorkflowGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWorkflowStructure = new WorkflowStructureElements();
		this.pWorkflow = new WorkflowElements();
		this.pMBoolExpr = new MBoolExprElements();
		this.pSequence = new SequenceElements();
		this.pTask = new TaskElements();
		this.pLoop = new LoopElements();
		this.pDecision = new DecisionElements();
		this.pEString = new EStringElements();
		this.pGuardedWorkflow = new GuardedWorkflowElements();
		this.pMBoolExpr_Impl = new MBoolExpr_ImplElements();
		this.pValue = new ValueElements();
		this.pBoolValue = new BoolValueElements();
		this.pBoolComp = new BoolCompElements();
		this.pNot = new NotElements();
		this.pRelComp = new RelCompElements();
		this.pAtom = new AtomElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.eBoolOp = new BoolOpElements();
		this.eRelOp = new RelOpElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("agent.adaption.xtext.workflow.Workflow".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//WorkflowStructure returns WorkflowStructure:
	//    'WorkflowStructure'
	//    '{'
	//        'workflowspec' workflowspec=Workflow
	//    '}';
	public WorkflowStructureElements getWorkflowStructureAccess() {
		return pWorkflowStructure;
	}
	
	public ParserRule getWorkflowStructureRule() {
		return getWorkflowStructureAccess().getRule();
	}
	
	//Workflow returns Workflow:
	//    Sequence | Task | Loop | Decision;
	public WorkflowElements getWorkflowAccess() {
		return pWorkflow;
	}
	
	public ParserRule getWorkflowRule() {
		return getWorkflowAccess().getRule();
	}
	
	//MBoolExpr returns MBoolExpr:
	//    MBoolExpr_Impl | Value | BoolValue | BoolComp | Not | RelComp | Atom;
	public MBoolExprElements getMBoolExprAccess() {
		return pMBoolExpr;
	}
	
	public ParserRule getMBoolExprRule() {
		return getMBoolExprAccess().getRule();
	}
	
	//Sequence returns Sequence:
	//    'Sequence'
	//    '{'
	//        'subworkflows' '{' subworkflows+=Workflow ( "," subworkflows+=Workflow)* '}'
	//    '}';
	public SequenceElements getSequenceAccess() {
		return pSequence;
	}
	
	public ParserRule getSequenceRule() {
		return getSequenceAccess().getRule();
	}
	
	//Task returns Task:
	//    'Task'
	//    '{'
	//        'ID' ID=EString
	//    '}';
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//Loop returns Loop:
	//    'Loop'
	//    '{'
	//        'loop' loop=GuardedWorkflow
	//    '}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//Decision returns Decision:
	//    'Decision'
	//    '{'
	//        'options' '{' options+=GuardedWorkflow ( "," options+=GuardedWorkflow)* '}'
	//    '}';
	public DecisionElements getDecisionAccess() {
		return pDecision;
	}
	
	public ParserRule getDecisionRule() {
		return getDecisionAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//GuardedWorkflow returns GuardedWorkflow:
	//    'GuardedWorkflow'
	//    '{'
	//        'body' body=Workflow
	//        'guard' guard=MBoolExpr
	//    '}';
	public GuardedWorkflowElements getGuardedWorkflowAccess() {
		return pGuardedWorkflow;
	}
	
	public ParserRule getGuardedWorkflowRule() {
		return getGuardedWorkflowAccess().getRule();
	}
	
	//MBoolExpr_Impl returns MBoolExpr:
	//    {MBoolExpr}
	//    'MBoolExpr'
	//    ;
	public MBoolExpr_ImplElements getMBoolExpr_ImplAccess() {
		return pMBoolExpr_Impl;
	}
	
	public ParserRule getMBoolExpr_ImplRule() {
		return getMBoolExpr_ImplAccess().getRule();
	}
	
	//Value returns Value:
	//    {Value}
	//    'Value'
	//    '{'
	//        ('value' value=EInt)?
	//    '}';
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//BoolValue returns BoolValue:
	//    {BoolValue}
	//    (value?='value')?
	//    'BoolValue'
	//    ;
	public BoolValueElements getBoolValueAccess() {
		return pBoolValue;
	}
	
	public ParserRule getBoolValueRule() {
		return getBoolValueAccess().getRule();
	}
	
	//BoolComp returns BoolComp:
	//    {BoolComp}
	//    'BoolComp'
	//    '{'
	//        ('op' op=BoolOp)?
	//        ('right' right=MBoolExpr)?
	//        ('left' left=MBoolExpr)?
	//    '}';
	public BoolCompElements getBoolCompAccess() {
		return pBoolComp;
	}
	
	public ParserRule getBoolCompRule() {
		return getBoolCompAccess().getRule();
	}
	
	//Not returns Not:
	//    {Not}
	//    'Not'
	//    '{'
	//        ('op' op=EString)?
	//        ('expr' expr=MBoolExpr)?
	//    '}';
	public NotElements getNotAccess() {
		return pNot;
	}
	
	public ParserRule getNotRule() {
		return getNotAccess().getRule();
	}
	
	//RelComp returns RelComp:
	//    {RelComp}
	//    'RelComp'
	//    '{'
	//        ('op' op=RelOp)?
	//        ('left' left=MBoolExpr)?
	//        ('right' right=MBoolExpr)?
	//    '}';
	public RelCompElements getRelCompAccess() {
		return pRelComp;
	}
	
	public ParserRule getRelCompRule() {
		return getRelCompAccess().getRule();
	}
	
	//Atom returns Atom:
	//    {Atom}
	//    'Atom'
	//    '{'
	//        ('measureID' measureID=EString)?
	//    '}';
	public AtomElements getAtomAccess() {
		return pAtom;
	}
	
	public ParserRule getAtomRule() {
		return getAtomAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum BoolOp returns BoolOp:
	//                AND = 'AND' | OR = 'OR';
	public BoolOpElements getBoolOpAccess() {
		return eBoolOp;
	}
	
	public EnumRule getBoolOpRule() {
		return getBoolOpAccess().getRule();
	}
	
	//enum RelOp returns RelOp:
	//                LESS_THAN = 'LESS_THAN' | GREATER_THAN = 'GREATER_THAN' | NOT_EQUAL = 'NOT_EQUAL' | LESS_EQUAL = 'LESS_EQUAL' | GREATER_EQUAL = 'GREATER_EQUAL' | EQUAL = 'EQUAL';
	public RelOpElements getRelOpAccess() {
		return eRelOp;
	}
	
	public EnumRule getRelOpRule() {
		return getRelOpAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
