/*
 * generated by Xtext 2.40.0
 */
grammar InternalWorkflow;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package agent.adaption.xtext.workflow.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package agent.adaption.xtext.workflow.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import agent.adaption.xtext.workflow.services.WorkflowGrammarAccess;

}

@parser::members {

 	private WorkflowGrammarAccess grammarAccess;

    public InternalWorkflowParser(TokenStream input, WorkflowGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "WorkflowStructure";
   	}

   	@Override
   	protected WorkflowGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleWorkflowStructure
entryRuleWorkflowStructure returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getWorkflowStructureRule()); }
	iv_ruleWorkflowStructure=ruleWorkflowStructure
	{ $current=$iv_ruleWorkflowStructure.current; }
	EOF;

// Rule WorkflowStructure
ruleWorkflowStructure returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='WorkflowStructure'
		{
			newLeafNode(otherlv_0, grammarAccess.getWorkflowStructureAccess().getWorkflowStructureKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getWorkflowStructureAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='workflowspec'
		{
			newLeafNode(otherlv_2, grammarAccess.getWorkflowStructureAccess().getWorkflowspecKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getWorkflowStructureAccess().getWorkflowspecWorkflowParserRuleCall_3_0());
				}
				lv_workflowspec_3_0=ruleWorkflow
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getWorkflowStructureRule());
					}
					set(
						$current,
						"workflowspec",
						lv_workflowspec_3_0,
						"agent.adaption.xtext.workflow.Workflow.Workflow");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getWorkflowStructureAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleWorkflow
entryRuleWorkflow returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getWorkflowRule()); }
	iv_ruleWorkflow=ruleWorkflow
	{ $current=$iv_ruleWorkflow.current; }
	EOF;

// Rule Workflow
ruleWorkflow returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getWorkflowAccess().getSequenceParserRuleCall_0());
		}
		this_Sequence_0=ruleSequence
		{
			$current = $this_Sequence_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getWorkflowAccess().getTaskParserRuleCall_1());
		}
		this_Task_1=ruleTask
		{
			$current = $this_Task_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getWorkflowAccess().getLoopParserRuleCall_2());
		}
		this_Loop_2=ruleLoop
		{
			$current = $this_Loop_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getWorkflowAccess().getDecisionParserRuleCall_3());
		}
		this_Decision_3=ruleDecision
		{
			$current = $this_Decision_3.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleMBoolExpr
entryRuleMBoolExpr returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMBoolExprRule()); }
	iv_ruleMBoolExpr=ruleMBoolExpr
	{ $current=$iv_ruleMBoolExpr.current; }
	EOF;

// Rule MBoolExpr
ruleMBoolExpr returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getMBoolExpr_ImplParserRuleCall_0());
		}
		this_MBoolExpr_Impl_0=ruleMBoolExpr_Impl
		{
			$current = $this_MBoolExpr_Impl_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getValueParserRuleCall_1());
		}
		this_Value_1=ruleValue
		{
			$current = $this_Value_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getBoolValueParserRuleCall_2());
		}
		this_BoolValue_2=ruleBoolValue
		{
			$current = $this_BoolValue_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getBoolCompParserRuleCall_3());
		}
		this_BoolComp_3=ruleBoolComp
		{
			$current = $this_BoolComp_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getNotParserRuleCall_4());
		}
		this_Not_4=ruleNot
		{
			$current = $this_Not_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getRelCompParserRuleCall_5());
		}
		this_RelComp_5=ruleRelComp
		{
			$current = $this_RelComp_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getMBoolExprAccess().getAtomParserRuleCall_6());
		}
		this_Atom_6=ruleAtom
		{
			$current = $this_Atom_6.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleSequence
entryRuleSequence returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSequenceRule()); }
	iv_ruleSequence=ruleSequence
	{ $current=$iv_ruleSequence.current; }
	EOF;

// Rule Sequence
ruleSequence returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Sequence'
		{
			newLeafNode(otherlv_0, grammarAccess.getSequenceAccess().getSequenceKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='subworkflows'
		{
			newLeafNode(otherlv_2, grammarAccess.getSequenceAccess().getSubworkflowsKeyword_2());
		}
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getSequenceAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_4_0());
				}
				lv_subworkflows_4_0=ruleWorkflow
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSequenceRule());
					}
					add(
						$current,
						"subworkflows",
						lv_subworkflows_4_0,
						"agent.adaption.xtext.workflow.Workflow.Workflow");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getSequenceAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getSequenceAccess().getSubworkflowsWorkflowParserRuleCall_5_1_0());
					}
					lv_subworkflows_6_0=ruleWorkflow
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSequenceRule());
						}
						add(
							$current,
							"subworkflows",
							lv_subworkflows_6_0,
							"agent.adaption.xtext.workflow.Workflow.Workflow");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_6());
		}
		otherlv_8='}'
		{
			newLeafNode(otherlv_8, grammarAccess.getSequenceAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleTask
entryRuleTask returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTaskRule()); }
	iv_ruleTask=ruleTask
	{ $current=$iv_ruleTask.current; }
	EOF;

// Rule Task
ruleTask returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Task'
		{
			newLeafNode(otherlv_0, grammarAccess.getTaskAccess().getTaskKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getTaskAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='ID'
		{
			newLeafNode(otherlv_2, grammarAccess.getTaskAccess().getIDKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTaskAccess().getIDEStringParserRuleCall_3_0());
				}
				lv_ID_3_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTaskRule());
					}
					set(
						$current,
						"ID",
						lv_ID_3_0,
						"agent.adaption.xtext.workflow.Workflow.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getTaskAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleLoop
entryRuleLoop returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLoopRule()); }
	iv_ruleLoop=ruleLoop
	{ $current=$iv_ruleLoop.current; }
	EOF;

// Rule Loop
ruleLoop returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Loop'
		{
			newLeafNode(otherlv_0, grammarAccess.getLoopAccess().getLoopKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getLoopAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='loop'
		{
			newLeafNode(otherlv_2, grammarAccess.getLoopAccess().getLoopKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLoopAccess().getLoopGuardedWorkflowParserRuleCall_3_0());
				}
				lv_loop_3_0=ruleGuardedWorkflow
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLoopRule());
					}
					set(
						$current,
						"loop",
						lv_loop_3_0,
						"agent.adaption.xtext.workflow.Workflow.GuardedWorkflow");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getLoopAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleDecision
entryRuleDecision returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDecisionRule()); }
	iv_ruleDecision=ruleDecision
	{ $current=$iv_ruleDecision.current; }
	EOF;

// Rule Decision
ruleDecision returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Decision'
		{
			newLeafNode(otherlv_0, grammarAccess.getDecisionAccess().getDecisionKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='options'
		{
			newLeafNode(otherlv_2, grammarAccess.getDecisionAccess().getOptionsKeyword_2());
		}
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getDecisionAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_4_0());
				}
				lv_options_4_0=ruleGuardedWorkflow
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDecisionRule());
					}
					add(
						$current,
						"options",
						lv_options_4_0,
						"agent.adaption.xtext.workflow.Workflow.GuardedWorkflow");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getDecisionAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getDecisionAccess().getOptionsGuardedWorkflowParserRuleCall_5_1_0());
					}
					lv_options_6_0=ruleGuardedWorkflow
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getDecisionRule());
						}
						add(
							$current,
							"options",
							lv_options_6_0,
							"agent.adaption.xtext.workflow.Workflow.GuardedWorkflow");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_6());
		}
		otherlv_8='}'
		{
			newLeafNode(otherlv_8, grammarAccess.getDecisionAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleGuardedWorkflow
entryRuleGuardedWorkflow returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getGuardedWorkflowRule()); }
	iv_ruleGuardedWorkflow=ruleGuardedWorkflow
	{ $current=$iv_ruleGuardedWorkflow.current; }
	EOF;

// Rule GuardedWorkflow
ruleGuardedWorkflow returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='GuardedWorkflow'
		{
			newLeafNode(otherlv_0, grammarAccess.getGuardedWorkflowAccess().getGuardedWorkflowKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getGuardedWorkflowAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='body'
		{
			newLeafNode(otherlv_2, grammarAccess.getGuardedWorkflowAccess().getBodyKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGuardedWorkflowAccess().getBodyWorkflowParserRuleCall_3_0());
				}
				lv_body_3_0=ruleWorkflow
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGuardedWorkflowRule());
					}
					set(
						$current,
						"body",
						lv_body_3_0,
						"agent.adaption.xtext.workflow.Workflow.Workflow");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='guard'
		{
			newLeafNode(otherlv_4, grammarAccess.getGuardedWorkflowAccess().getGuardKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGuardedWorkflowAccess().getGuardMBoolExprParserRuleCall_5_0());
				}
				lv_guard_5_0=ruleMBoolExpr
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGuardedWorkflowRule());
					}
					set(
						$current,
						"guard",
						lv_guard_5_0,
						"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getGuardedWorkflowAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleMBoolExpr_Impl
entryRuleMBoolExpr_Impl returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMBoolExpr_ImplRule()); }
	iv_ruleMBoolExpr_Impl=ruleMBoolExpr_Impl
	{ $current=$iv_ruleMBoolExpr_Impl.current; }
	EOF;

// Rule MBoolExpr_Impl
ruleMBoolExpr_Impl returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprAction_0(),
					$current);
			}
		)
		otherlv_1='MBoolExpr'
		{
			newLeafNode(otherlv_1, grammarAccess.getMBoolExpr_ImplAccess().getMBoolExprKeyword_1());
		}
	)
;

// Entry rule entryRuleValue
entryRuleValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getValueRule()); }
	iv_ruleValue=ruleValue
	{ $current=$iv_ruleValue.current; }
	EOF;

// Rule Value
ruleValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getValueAccess().getValueAction_0(),
					$current);
			}
		)
		otherlv_1='Value'
		{
			newLeafNode(otherlv_1, grammarAccess.getValueAccess().getValueKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getValueAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='value'
			{
				newLeafNode(otherlv_3, grammarAccess.getValueAccess().getValueKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getValueAccess().getValueEIntParserRuleCall_3_1_0());
					}
					lv_value_4_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getValueRule());
						}
						set(
							$current,
							"value",
							lv_value_4_0,
							"agent.adaption.xtext.workflow.Workflow.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getValueAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleBoolValue
entryRuleBoolValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBoolValueRule()); }
	iv_ruleBoolValue=ruleBoolValue
	{ $current=$iv_ruleBoolValue.current; }
	EOF;

// Rule BoolValue
ruleBoolValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getBoolValueAccess().getBoolValueAction_0(),
					$current);
			}
		)
		(
			(
				lv_value_1_0='value'
				{
					newLeafNode(lv_value_1_0, grammarAccess.getBoolValueAccess().getValueValueKeyword_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBoolValueRule());
					}
					setWithLastConsumed($current, "value", lv_value_1_0 != null, "value");
				}
			)
		)?
		otherlv_2='BoolValue'
		{
			newLeafNode(otherlv_2, grammarAccess.getBoolValueAccess().getBoolValueKeyword_2());
		}
	)
;

// Entry rule entryRuleBoolComp
entryRuleBoolComp returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBoolCompRule()); }
	iv_ruleBoolComp=ruleBoolComp
	{ $current=$iv_ruleBoolComp.current; }
	EOF;

// Rule BoolComp
ruleBoolComp returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getBoolCompAccess().getBoolCompAction_0(),
					$current);
			}
		)
		otherlv_1='BoolComp'
		{
			newLeafNode(otherlv_1, grammarAccess.getBoolCompAccess().getBoolCompKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getBoolCompAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='op'
			{
				newLeafNode(otherlv_3, grammarAccess.getBoolCompAccess().getOpKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBoolCompAccess().getOpBoolOpEnumRuleCall_3_1_0());
					}
					lv_op_4_0=ruleBoolOp
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBoolCompRule());
						}
						set(
							$current,
							"op",
							lv_op_4_0,
							"agent.adaption.xtext.workflow.Workflow.BoolOp");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='right'
			{
				newLeafNode(otherlv_5, grammarAccess.getBoolCompAccess().getRightKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBoolCompAccess().getRightMBoolExprParserRuleCall_4_1_0());
					}
					lv_right_6_0=ruleMBoolExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBoolCompRule());
						}
						set(
							$current,
							"right",
							lv_right_6_0,
							"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_7='left'
			{
				newLeafNode(otherlv_7, grammarAccess.getBoolCompAccess().getLeftKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getBoolCompAccess().getLeftMBoolExprParserRuleCall_5_1_0());
					}
					lv_left_8_0=ruleMBoolExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getBoolCompRule());
						}
						set(
							$current,
							"left",
							lv_left_8_0,
							"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getBoolCompAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleNot
entryRuleNot returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNotRule()); }
	iv_ruleNot=ruleNot
	{ $current=$iv_ruleNot.current; }
	EOF;

// Rule Not
ruleNot returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getNotAccess().getNotAction_0(),
					$current);
			}
		)
		otherlv_1='Not'
		{
			newLeafNode(otherlv_1, grammarAccess.getNotAccess().getNotKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getNotAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='op'
			{
				newLeafNode(otherlv_3, grammarAccess.getNotAccess().getOpKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getNotAccess().getOpEStringParserRuleCall_3_1_0());
					}
					lv_op_4_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNotRule());
						}
						set(
							$current,
							"op",
							lv_op_4_0,
							"agent.adaption.xtext.workflow.Workflow.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='expr'
			{
				newLeafNode(otherlv_5, grammarAccess.getNotAccess().getExprKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getNotAccess().getExprMBoolExprParserRuleCall_4_1_0());
					}
					lv_expr_6_0=ruleMBoolExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNotRule());
						}
						set(
							$current,
							"expr",
							lv_expr_6_0,
							"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getNotAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleRelComp
entryRuleRelComp returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRelCompRule()); }
	iv_ruleRelComp=ruleRelComp
	{ $current=$iv_ruleRelComp.current; }
	EOF;

// Rule RelComp
ruleRelComp returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getRelCompAccess().getRelCompAction_0(),
					$current);
			}
		)
		otherlv_1='RelComp'
		{
			newLeafNode(otherlv_1, grammarAccess.getRelCompAccess().getRelCompKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getRelCompAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='op'
			{
				newLeafNode(otherlv_3, grammarAccess.getRelCompAccess().getOpKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRelCompAccess().getOpRelOpEnumRuleCall_3_1_0());
					}
					lv_op_4_0=ruleRelOp
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRelCompRule());
						}
						set(
							$current,
							"op",
							lv_op_4_0,
							"agent.adaption.xtext.workflow.Workflow.RelOp");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_5='left'
			{
				newLeafNode(otherlv_5, grammarAccess.getRelCompAccess().getLeftKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRelCompAccess().getLeftMBoolExprParserRuleCall_4_1_0());
					}
					lv_left_6_0=ruleMBoolExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRelCompRule());
						}
						set(
							$current,
							"left",
							lv_left_6_0,
							"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_7='right'
			{
				newLeafNode(otherlv_7, grammarAccess.getRelCompAccess().getRightKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRelCompAccess().getRightMBoolExprParserRuleCall_5_1_0());
					}
					lv_right_8_0=ruleMBoolExpr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRelCompRule());
						}
						set(
							$current,
							"right",
							lv_right_8_0,
							"agent.adaption.xtext.workflow.Workflow.MBoolExpr");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getRelCompAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleAtom
entryRuleAtom returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAtomRule()); }
	iv_ruleAtom=ruleAtom
	{ $current=$iv_ruleAtom.current; }
	EOF;

// Rule Atom
ruleAtom returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getAtomAccess().getAtomAction_0(),
					$current);
			}
		)
		otherlv_1='Atom'
		{
			newLeafNode(otherlv_1, grammarAccess.getAtomAccess().getAtomKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getAtomAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='measureID'
			{
				newLeafNode(otherlv_3, grammarAccess.getAtomAccess().getMeasureIDKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAtomAccess().getMeasureIDEStringParserRuleCall_3_1_0());
					}
					lv_measureID_4_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAtomRule());
						}
						set(
							$current,
							"measureID",
							lv_measureID_4_0,
							"agent.adaption.xtext.workflow.Workflow.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getAtomAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleEInt
entryRuleEInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEIntRule()); }
	iv_ruleEInt=ruleEInt
	{ $current=$iv_ruleEInt.current.getText(); }
	EOF;

// Rule EInt
ruleEInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEIntAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getEIntAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Rule BoolOp
ruleBoolOp returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='AND'
			{
				$current = grammarAccess.getBoolOpAccess().getANDEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getBoolOpAccess().getANDEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='OR'
			{
				$current = grammarAccess.getBoolOpAccess().getOREnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getBoolOpAccess().getOREnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule RelOp
ruleRelOp returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='LESS_THAN'
			{
				$current = grammarAccess.getRelOpAccess().getLESS_THANEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getRelOpAccess().getLESS_THANEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='GREATER_THAN'
			{
				$current = grammarAccess.getRelOpAccess().getGREATER_THANEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getRelOpAccess().getGREATER_THANEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='NOT_EQUAL'
			{
				$current = grammarAccess.getRelOpAccess().getNOT_EQUALEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getRelOpAccess().getNOT_EQUALEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='LESS_EQUAL'
			{
				$current = grammarAccess.getRelOpAccess().getLESS_EQUALEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getRelOpAccess().getLESS_EQUALEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='GREATER_EQUAL'
			{
				$current = grammarAccess.getRelOpAccess().getGREATER_EQUALEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getRelOpAccess().getGREATER_EQUALEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='EQUAL'
			{
				$current = grammarAccess.getRelOpAccess().getEQUALEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getRelOpAccess().getEQUALEnumLiteralDeclaration_5());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
