/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.ui.tests;

import agent.adaption.xtext.workflow.ui.internal.WorkflowActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WorkflowUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WorkflowActivator.getInstance().getInjector("agent.adaption.xtext.workflow.Workflow");
	}

}
