/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.ui;

import agent.adaption.xtext.workflow.ui.internal.WorkflowActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WorkflowExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(WorkflowActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		WorkflowActivator activator = WorkflowActivator.getInstance();
		return activator != null ? activator.getInjector(WorkflowActivator.AGENT_ADAPTION_XTEXT_WORKFLOW_WORKFLOW) : null;
	}

}
