/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.formatting2

import agent.adaption.xtext.workflow.services.WorkflowGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import workflowspec.Sequence
import workflowspec.WorkflowStructure

class WorkflowFormatter extends AbstractFormatter2 {
	
	@Inject extension WorkflowGrammarAccess

	def dispatch void format(WorkflowStructure workflowStructure, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		workflowStructure.workflowspec.format
	}

	def dispatch void format(Sequence sequence, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (workflow : sequence.subworkflows) {
			workflow.format
		}
	}
	
	// TODO: implement for Loop, Decision, GuardedWorkflow, BoolComp, Not, RelComp
}
