/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WorkflowRuntimeModule extends AbstractWorkflowRuntimeModule {
}
