/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.ide;

import agent.adaption.xtext.workflow.WorkflowRuntimeModule;
import agent.adaption.xtext.workflow.WorkflowStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WorkflowIdeSetup extends WorkflowStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WorkflowRuntimeModule(), new WorkflowIdeModule()));
	}
	
}
