/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.ide;


/**
 * Use this class to register ide components.
 */
public class WorkflowIdeModule extends AbstractWorkflowIdeModule {
}
