/*
 * generated by Xtext 2.40.0
 */
package agent.adaption.xtext.workflow.ide.contentassist.antlr;

import agent.adaption.xtext.workflow.ide.contentassist.antlr.internal.InternalWorkflowParser;
import agent.adaption.xtext.workflow.services.WorkflowGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class WorkflowParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(WorkflowGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, WorkflowGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getWorkflowAccess().getAlternatives(), "rule__Workflow__Alternatives");
			builder.put(grammarAccess.getMBoolExprAccess().getAlternatives(), "rule__MBoolExpr__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getBoolOpAccess().getAlternatives(), "rule__BoolOp__Alternatives");
			builder.put(grammarAccess.getRelOpAccess().getAlternatives(), "rule__RelOp__Alternatives");
			builder.put(grammarAccess.getWorkflowStructureAccess().getGroup(), "rule__WorkflowStructure__Group__0");
			builder.put(grammarAccess.getSequenceAccess().getGroup(), "rule__Sequence__Group__0");
			builder.put(grammarAccess.getSequenceAccess().getGroup_5(), "rule__Sequence__Group_5__0");
			builder.put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
			builder.put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
			builder.put(grammarAccess.getDecisionAccess().getGroup(), "rule__Decision__Group__0");
			builder.put(grammarAccess.getDecisionAccess().getGroup_5(), "rule__Decision__Group_5__0");
			builder.put(grammarAccess.getGuardedWorkflowAccess().getGroup(), "rule__GuardedWorkflow__Group__0");
			builder.put(grammarAccess.getMBoolExpr_ImplAccess().getGroup(), "rule__MBoolExpr_Impl__Group__0");
			builder.put(grammarAccess.getValueAccess().getGroup(), "rule__Value__Group__0");
			builder.put(grammarAccess.getValueAccess().getGroup_3(), "rule__Value__Group_3__0");
			builder.put(grammarAccess.getBoolValueAccess().getGroup(), "rule__BoolValue__Group__0");
			builder.put(grammarAccess.getBoolCompAccess().getGroup(), "rule__BoolComp__Group__0");
			builder.put(grammarAccess.getBoolCompAccess().getGroup_3(), "rule__BoolComp__Group_3__0");
			builder.put(grammarAccess.getBoolCompAccess().getGroup_4(), "rule__BoolComp__Group_4__0");
			builder.put(grammarAccess.getBoolCompAccess().getGroup_5(), "rule__BoolComp__Group_5__0");
			builder.put(grammarAccess.getNotAccess().getGroup(), "rule__Not__Group__0");
			builder.put(grammarAccess.getNotAccess().getGroup_3(), "rule__Not__Group_3__0");
			builder.put(grammarAccess.getNotAccess().getGroup_4(), "rule__Not__Group_4__0");
			builder.put(grammarAccess.getRelCompAccess().getGroup(), "rule__RelComp__Group__0");
			builder.put(grammarAccess.getRelCompAccess().getGroup_3(), "rule__RelComp__Group_3__0");
			builder.put(grammarAccess.getRelCompAccess().getGroup_4(), "rule__RelComp__Group_4__0");
			builder.put(grammarAccess.getRelCompAccess().getGroup_5(), "rule__RelComp__Group_5__0");
			builder.put(grammarAccess.getAtomAccess().getGroup(), "rule__Atom__Group__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_3(), "rule__Atom__Group_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getWorkflowStructureAccess().getWorkflowspecAssignment_3(), "rule__WorkflowStructure__WorkflowspecAssignment_3");
			builder.put(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_4(), "rule__Sequence__SubworkflowsAssignment_4");
			builder.put(grammarAccess.getSequenceAccess().getSubworkflowsAssignment_5_1(), "rule__Sequence__SubworkflowsAssignment_5_1");
			builder.put(grammarAccess.getTaskAccess().getIDAssignment_3(), "rule__Task__IDAssignment_3");
			builder.put(grammarAccess.getLoopAccess().getLoopAssignment_3(), "rule__Loop__LoopAssignment_3");
			builder.put(grammarAccess.getDecisionAccess().getOptionsAssignment_4(), "rule__Decision__OptionsAssignment_4");
			builder.put(grammarAccess.getDecisionAccess().getOptionsAssignment_5_1(), "rule__Decision__OptionsAssignment_5_1");
			builder.put(grammarAccess.getGuardedWorkflowAccess().getBodyAssignment_3(), "rule__GuardedWorkflow__BodyAssignment_3");
			builder.put(grammarAccess.getGuardedWorkflowAccess().getGuardAssignment_5(), "rule__GuardedWorkflow__GuardAssignment_5");
			builder.put(grammarAccess.getValueAccess().getValueAssignment_3_1(), "rule__Value__ValueAssignment_3_1");
			builder.put(grammarAccess.getBoolValueAccess().getValueAssignment_1(), "rule__BoolValue__ValueAssignment_1");
			builder.put(grammarAccess.getBoolCompAccess().getOpAssignment_3_1(), "rule__BoolComp__OpAssignment_3_1");
			builder.put(grammarAccess.getBoolCompAccess().getRightAssignment_4_1(), "rule__BoolComp__RightAssignment_4_1");
			builder.put(grammarAccess.getBoolCompAccess().getLeftAssignment_5_1(), "rule__BoolComp__LeftAssignment_5_1");
			builder.put(grammarAccess.getNotAccess().getOpAssignment_3_1(), "rule__Not__OpAssignment_3_1");
			builder.put(grammarAccess.getNotAccess().getExprAssignment_4_1(), "rule__Not__ExprAssignment_4_1");
			builder.put(grammarAccess.getRelCompAccess().getOpAssignment_3_1(), "rule__RelComp__OpAssignment_3_1");
			builder.put(grammarAccess.getRelCompAccess().getLeftAssignment_4_1(), "rule__RelComp__LeftAssignment_4_1");
			builder.put(grammarAccess.getRelCompAccess().getRightAssignment_5_1(), "rule__RelComp__RightAssignment_5_1");
			builder.put(grammarAccess.getAtomAccess().getMeasureIDAssignment_3_1(), "rule__Atom__MeasureIDAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private WorkflowGrammarAccess grammarAccess;

	@Override
	protected InternalWorkflowParser createParser() {
		InternalWorkflowParser result = new InternalWorkflowParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public WorkflowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WorkflowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
